import './style.css';
import * as THREE from 'three';
import {GameWorld,trackPoint} from './world.js';
import {FlightInput,AIM_LIMITS,lockRadius} from './input.js';
import {GameAudio} from './audio.js';
import {LandscapeMode} from './landscape.js';
import {LockSystem,clamp,damp,segmentSphere,seeded,WAVE_TIMES} from './combat.js';

const $=id=>document.getElementById(id), show=(id,on)=>$(id).classList.toggle('hidden',!on);
const params=new URLSearchParams(location.search),debug=params.has('debug'),auto=debug&&params.has('autopilot'),speed=debug?clamp(Number(params.get('speed'))||1,1,8):1;
const audio=new GameAudio,locks=new LockSystem,fx=$('effects'),ctx=fx.getContext('2d');
let world,input,landscape,state='loading',previous=performance.now(),elapsed=0,distance=0,hp=100,score=0,kills=0,chain=1,chainTime=0,wave=0,shotTimer=0,invincible=0,finishTimer=0,flash=0,messageTimer=0,boss=null,bank=0,heroSide=0,heroHeight=7,rng=seeded(21),frame=0,fps=60;
let enemies=[],shots=[],bullets=[],lasers=[],particles=[],rings=[];let stats={lasers:0,locks:0,shots:0,hits:0};
for(let i=0;i<8;i++)$('lock-slots').append(document.createElement('i'));
function message(text,time=3){$('message').textContent=text;messageTimer=time;$('message').classList.add('visible');}
function reset(){world.clearDynamic();enemies=[];shots=[];bullets=[];lasers=[];particles=[];rings=[];locks.clear();locks.cooldown=0;input.reset();input.aim={x:0,y:0};elapsed=0;distance=0;hp=100;score=0;kills=0;chain=1;chainTime=0;wave=0;shotTimer=0;invincible=0;finishTimer=0;flash=0;boss=null;heroSide=0;heroHeight=7;bank=0;rng=seeded(21);stats={lasers:0,locks:0,shots:0,hits:0};}
function start(){if(state==='loading')return;if(landscape?.blocked){landscape.request();return;}landscape?.request();if(state==='paused'){pause();return;}audio.unlock();reset();state='playing';input.enabled=true;world.hero.visible=true;world.hero.material.opacity=1;['menu','pause-panel','result','boss-hud'].forEach(id=>show(id,false));['hud','telemetry','pause'].forEach(id=>show(id,true));audio.bgm();message('OPERATION 01',4);}
function retry(){state='menu';start();}
function pause(onlyPause=false){if(state==='paused'&&landscape?.blocked)return;if(state==='playing'){state='paused';input.enabled=false;input.reset();locks.clear();show('pause-panel',true);audio.pause();}else if(state==='paused'&&!onlyPause){state='playing';input.enabled=true;show('pause-panel',false);audio.resume();}}
function title(){reset();state='menu';input.enabled=false;world.hero.visible=false;['result','hud','telemetry','pause','boss-hud'].forEach(id=>show(id,false));show('menu',true);audio.pause();}
function result(clear){state=clear?'clear':'dead';input.enabled=false;input.reset();locks.clear();audio.pause();show('result',true);show('pause',false);show('boss-hud',false);$('result-eyebrow').textContent=clear?'MISSION COMPLETE':'SIGNAL LOST';$('result-title').textContent=clear?'AREA SECURED':'FLIGHT LOST';$('result-score').textContent=score.toLocaleString();$('result-kills').textContent=kills;$('result-rank').textContent=clear?(score>65000?'S':score>30000?'A':'B'):'—';}
function disposableLine(points,color){const geometry=new THREE.BufferGeometry().setFromPoints(points),material=new THREE.LineBasicMaterial({color,transparent:true,opacity:.9,toneMapped:false});const line=new THREE.Line(geometry,material);line.userData.disposableGeometry=true;line.userData.ownMaterial=true;world.dynamic.add(line);return line;}
function removeMesh(mesh){world.dynamic.remove(mesh);if(mesh.userData.disposableGeometry)mesh.geometry.dispose();if(mesh.userData.ownMaterial)mesh.material.dispose();}
function clearProjectiles(){for(const projectile of [...shots,...bullets])removeMesh(projectile.mesh);for(const laser of lasers){removeMesh(laser.line);removeMesh(laser.head);}shots=[];bullets=[];lasers=[];}
function orb(kind,pos){const mesh=new THREE.Mesh(world.sharedGeometry[kind],world.sharedMaterial[kind]);mesh.position.copy(pos);world.dynamic.add(mesh);return mesh;}
function burst(pos,big=false){rings.push({pos:pos.clone(),age:0,big});for(let i=0;i<(big?36:12);i++){const mesh=orb('spark',pos);particles.push({mesh,vel:new THREE.Vector3((rng()-.5)*16,(rng()-.25)*13,(rng()-.5)*16),life:.35+rng()*.6,max:1});}audio.explosion(big);}
function targetPoint(e){return e.mesh.position.clone().add(new THREE.Vector3(0,e.boss?5:e.type==='turret'?1.7:0,0));}
function spawn(type,s,side,height){const mesh=world.cloneEnemy(type);world.dynamic.add(mesh);const e={id:++frame,type,boss:type==='boss',hp:type==='boss'?2200:type==='turret'?28:type==='interceptor'?20:12,maxHp:0,radius:type==='boss'?5:type==='turret'?1.8:1.4,s,side,baseSide:side,height,age:0,fire:1.8+rng()*2,mesh,removed:false};e.maxHp=e.hp;mesh.position.copy(trackPoint(s,side,height));world.orientToFlight(mesh,s);mesh.rotation.y+=Math.PI;enemies.push(e);return e;}
function spawnWave(index){const n=index%3===0?5:4;for(let i=0;i<n;i++)spawn(index%3===2?'interceptor':'scout',distance+140+i*11,(i-(n-1)/2)*3.2,7+(i%2)*3);if(index%3===1)spawn('turret',distance+165,index%2?9:-9,0);if(index===6)message('SECTOR 02');if(index===12)message('SECTOR 03');}
function damageEnemy(e,amount){if(e.removed||e.hp<=0)return;e.hp-=amount;if(e.hp>0)return;e.removed=true;kills++;chain=chainTime>0?Math.min(8,chain+1):1;chainTime=4;score+=(e.boss?6000:e.type==='turret'?240:160)*chain;burst(targetPoint(e),e.boss);removeMesh(e.mesh);if(e.boss){state='clearing';input.enabled=false;locks.clear();finishTimer=3;score+=Math.round(hp)*100;message('GRENDEL DOWN',3);}}
function damagePlayer(amount){if(state!=='playing'||invincible>0)return;stats.hits++;if(!(debug&&params.has('invulnerable')))hp=Math.max(0,hp-amount);invincible=1.1;flash=.7;chain=1;chainTime=0;audio.hit();if(hp<=0){burst(world.hero.position,true);world.hero.visible=false;result(false);}}
function fireBullet(e,angle=0,velocity=28){const pos=targetPoint(e),dir=world.hero.position.clone().sub(pos).normalize().applyAxisAngle(new THREE.Vector3(0,1,0),angle);const mesh=orb('bullet',pos);if(e.boss)mesh.scale.setScalar(1.7);bullets.push({mesh,vel:dir.multiplyScalar(velocity),life:8,radius:e.boss?.48:.3});}
function fireLaser(target,index,total){const from=world.hero.position.clone(),to=targetPoint(target),mid=from.clone().lerp(to,.5);mid.x+=(index-(total-1)/2)*4;mid.y+=4+Math.abs(index-(total-1)/2);const line=disposableLine(Array.from({length:18},()=>from.clone()),new THREE.Color(.25,2,3));lasers.push({target,from,mid,age:0,duration:.6+from.distanceTo(to)/230,line,head:orb('shot',from)});stats.lasers++;}
function autopilot(){const available=enemies.filter(e=>!e.removed&&e.s>distance+18).sort((a,b)=>a.s-b.s);const e=available[0];if(e){const p=world.project(targetPoint(e));input.aim.x=clamp(p.x,-.9,.9);input.aim.y=clamp(p.y,AIM_LIMITS.bottom,AIM_LIMITS.top);}const held=elapsed%1.5<1.2;if(input.held&&!held)input.released=true;input.held=held;}
function update(dt){elapsed+=dt;distance=Math.min(1680,elapsed*14);chainTime-=dt;if(chainTime<=0)chain=1;invincible=Math.max(0,invincible-dt);flash=Math.max(0,flash-dt*2);input.update(dt);if(auto)autopilot();if(input.cancelled){locks.clear();input.cancelled=false;}
  const lastSide=heroSide;heroSide=damp(heroSide,input.aim.x*(innerWidth<innerHeight?4.3:7.7),4,dt);heroHeight=damp(heroHeight,7+input.aim.y*4,4,dt);bank=damp(bank,(heroSide-lastSide)/Math.max(dt,.001)*.12,7,dt);world.setCamera(distance,bank);world.hero.position.copy(trackPoint(distance+14,heroSide,heroHeight));world.hero.material.rotation=-bank*.13;world.hero.material.opacity=invincible>0?(Math.sin(elapsed*45)>.1?.35:1):1;world.setHeroFrame(bank>.08?1:bank<-.08?2:0,Math.floor(elapsed*11)%4);
  while(wave<WAVE_TIMES.length&&elapsed>=WAVE_TIMES[wave])spawnWave(wave++);
  if(elapsed>=120&&!boss){boss=spawn('boss',1748,0,0);show('boss-hud',true);audio.bgm(true);message('WARNING / GRENDEL',4);}
  for(const e of enemies){if(e.removed)continue;e.age+=dt;if(!e.boss&&e.type!=='turret'){e.s-=dt*(e.type==='interceptor'?10:3);e.side=e.baseSide+Math.sin(e.age*1.2+e.id)*1.8;}if(e.boss)e.side=Math.sin(e.age*.55)*4;e.mesh.position.copy(trackPoint(e.s,e.side,e.height));if(e.boss){for(let i=1;i<e.mesh.children.length;i++)e.mesh.children[i].position.y=Math.sin(e.age*3+i*Math.PI)*.3;}else if(e.type!=='turret')e.mesh.rotation.z=Math.sin(e.age*1.2+e.id)*.12;
    e.fire-=dt;if(e.fire<0&&e.s>distance+24&&e.s<distance+155){const phase=e.boss?(e.hp/e.maxHp<.33?3:e.hp/e.maxHp<.66?2:1):0;if(phase){for(let i=-phase;i<=phase;i++)fireBullet(e,i*.075,24+phase*3);e.fire=1.6-phase*.2;}else{fireBullet(e,0,24);e.fire=3+rng()*2;}}
    if(e.s<distance+4){e.removed=true;removeMesh(e.mesh);}
  }
  const candidates=enemies.filter(e=>!e.removed&&e.s>distance+14).map(e=>{const p=world.project(targetPoint(e));return{e,p,d:Math.hypot((p.x-input.aim.x)*innerWidth/2,(p.y-input.aim.y)*innerHeight/2)};}).filter(t=>t.p.z<1&&t.p.z>0&&Math.abs(t.p.x)<1.1&&Math.abs(t.p.y)<1.1&&locks.targets.filter(e=>e===t.e).length<(t.e.boss?8:Math.min(3,Math.ceil(t.e.hp/11)))).sort((a,b)=>a.d-b.d);
  if(locks.update(dt,input.held,candidates[0]?.d<lockRadius(innerWidth,innerHeight)?candidates[0].e:null)){audio.lock(locks.targets.length);stats.locks++;}
  if(input.released){const targets=locks.release();targets.forEach((e,i)=>fireLaser(e,i,targets.length));if(targets.length)audio.laser();input.released=false;}
  shotTimer-=dt;if(shotTimer<=0){shotTimer=.105;const pos=world.hero.position.clone().add(new THREE.Vector3((stats.shots%2?1:-1)*.36,.3,-.3));const dir=world.aimPoint(input.aim,140).sub(pos).normalize();const mesh=orb('shot',pos);mesh.scale.set(.8,.8,4);shots.push({mesh,vel:dir.multiplyScalar(180),life:1.8});stats.shots++;}
  for(const shot of shots){const old=shot.mesh.position.clone();shot.mesh.position.addScaledVector(shot.vel,dt);shot.life-=dt;for(const e of enemies){if(!e.removed&&segmentSphere(old,shot.mesh.position,targetPoint(e),e.radius)){damageEnemy(e,2);shot.life=0;break;}}}
  for(const b of bullets){const old=b.mesh.position.clone();b.mesh.position.addScaledVector(b.vel,dt);b.life-=dt;if(segmentSphere(old,b.mesh.position,world.hero.position.clone().add(new THREE.Vector3(0,.45,0)),.55+b.radius)){damagePlayer(17);b.life=0;}}
  for(const l of lasers){l.age+=dt;const t=clamp(l.age/l.duration,0,1),to=targetPoint(l.target),curve=new THREE.QuadraticBezierCurve3(l.from,l.mid,to),arr=l.line.geometry.attributes.position;for(let i=0;i<arr.count;i++){const p=curve.getPoint(Math.max(0,t-i*.021));arr.setXYZ(i,p.x,p.y,p.z);}arr.needsUpdate=true;l.line.geometry.computeBoundingSphere();l.head.position.copy(curve.getPoint(t));if(t===1){damageEnemy(l.target,11);l.dead=true;removeMesh(l.line);removeMesh(l.head);}}
  shots=shots.filter(s=>{if(s.life<=0){removeMesh(s.mesh);return false;}return true;});bullets=bullets.filter(s=>{if(s.life<=0){removeMesh(s.mesh);return false;}return true;});lasers=lasers.filter(l=>!l.dead);enemies=enemies.filter(e=>!e.removed);updateParticles(dt);
}
function updateParticles(dt){for(const p of particles){p.life-=dt;p.mesh.position.addScaledVector(p.vel,dt);p.mesh.scale.setScalar(Math.max(0,p.life)*2);}particles=particles.filter(p=>{if(p.life<=0){removeMesh(p.mesh);return false;}return true;});for(const r of rings)r.age+=dt;rings=rings.filter(r=>r.age<.65);}
function drawFX(){const w=fx.width,h=fx.height;ctx.clearRect(0,0,w,h);if(!['playing','paused','clearing'].includes(state))return;const xy=p=>[(p.x+1)*w/2,(1-p.y)*h/2];
  for(const e of enemies){const p=world.project(targetPoint(e));if(p.z>1||p.z<0)continue;const [x,y]=xy(p),n=locks.targets.filter(t=>t===e).length;ctx.strokeStyle=n?'#9cfaff':'#ffd1ab';ctx.globalAlpha=n?.9:.3;const r=e.boss?42:14;if(n||Math.hypot((p.x-input.aim.x)*w/2,(p.y-input.aim.y)*h/2)<lockRadius(w,h)){ctx.lineWidth=n?1.5:1;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.stroke();ctx.font='11px monospace';ctx.fillStyle='#d4ffff';if(n)ctx.fillText(String(n),x+r+5,y+4);}if(e.fire<.55&&e.s<distance+110){ctx.strokeStyle='#ff638c';ctx.beginPath();ctx.arc(x,y,18+(1-e.fire/.55)*10,0,Math.PI*2);ctx.stroke();}}
  ctx.globalAlpha=1;ctx.shadowColor='#28caff';ctx.shadowBlur=14;
  for(const laser of lasers){const a=laser.line.geometry.attributes.position;ctx.beginPath();for(let i=0;i<a.count;i++){const p=world.project(new THREE.Vector3(a.getX(i),a.getY(i),a.getZ(i)));const [x,y]=xy(p);if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.strokeStyle='#50cfff';ctx.lineWidth=4;ctx.stroke();ctx.strokeStyle='#e2ffff';ctx.lineWidth=1.5;ctx.stroke();}ctx.shadowBlur=0;
  ctx.globalAlpha=1;
  if(input.touchPad){
    const pad=input.touchPad,length=Math.hypot(pad.dx,pad.dy),factor=length?Math.min(1,pad.radius/length):0;
    ctx.strokeStyle='#b7e8ff';ctx.lineWidth=1.5;ctx.globalAlpha=.25;ctx.beginPath();ctx.arc(pad.x,pad.y,pad.radius,0,Math.PI*2);ctx.stroke();
    ctx.globalAlpha=.45;ctx.beginPath();ctx.arc(pad.x+pad.dx*factor,pad.y+pad.dy*factor,14,0,Math.PI*2);ctx.stroke();
  }
  const [x,y]=xy(input.aim),r=lockRadius(w,h);
  // The visible ring and acquisition radius use the same screen pixels.
  ctx.globalAlpha=input.held?.55:.25;ctx.strokeStyle='#83e8ff';ctx.lineWidth=1;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.stroke();
  ctx.globalAlpha=1;ctx.strokeStyle=input.held?'#dcffff':'#7ce7ff';ctx.lineWidth=2.5;ctx.beginPath();
  for(let i=0;i<4;i++){const a=i*Math.PI/2+Math.PI/4;ctx.moveTo(x+Math.cos(a-.24)*r,y+Math.sin(a-.24)*r);ctx.arc(x,y,r,a-.24,a+.24);}
  ctx.moveTo(x-10,y);ctx.lineTo(x+10,y);ctx.moveTo(x,y-10);ctx.lineTo(x,y+10);ctx.stroke();ctx.fillStyle='#ecffff';ctx.fillRect(x-1.5,y-1.5,3,3);
  for(const r of rings){const p=world.project(r.pos);if(p.z>1)continue;const [x,y]=xy(p);ctx.globalAlpha=(1-r.age/.65)*.8;ctx.strokeStyle=r.big?'#ffce87':'#9ff6ff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,(r.big?160:45)*r.age+5,0,Math.PI*2);ctx.stroke();}ctx.globalAlpha=1;if(flash>0){const g=ctx.createRadialGradient(w/2,h/2,h*.2,w/2,h/2,w*.6);g.addColorStop(0,'#ff315000');g.addColorStop(1,`rgba(255,30,70,${flash*.6})`);ctx.fillStyle=g;ctx.fillRect(0,0,w,h);}}
function hud(){const sec=Math.floor(elapsed);$('score').textContent=String(score).padStart(7,'0');$('combo').textContent=`CHAIN ×${chain}`;$('hp-number').textContent=Math.ceil(hp);$('hp-fill').style.width=hp+'%';$('status').textContent=hp<35?'ARMOR CRITICAL':'SYSTEM NOMINAL';$('progress-fill').style.width=Math.min(100,elapsed/120*100)+'%';$('mission-time').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')} / ${boss?'GRENDEL ENGAGED':'CITY APPROACH'}`;$('sector').textContent=elapsed<43?'MIDNIGHT BOULEVARD':elapsed<85?'UNDERPASS DISTRICT':'CENTRAL SPIRE';$('lock-label').textContent=locks.targets.length?`LOCKED ${locks.targets.length} / 8`:input.held?'SCANNING':'MULTI LOCK';[...$('lock-slots').children].forEach((el,i)=>el.classList.toggle('active',i<locks.targets.length));if(boss){$('boss-hp').style.width=Math.max(0,boss.hp/boss.maxHp*100)+'%';$('boss-phase').textContent=`JOY DRIVE / PHASE ${boss.hp/boss.maxHp<.33?'03':boss.hp/boss.maxHp<.66?'02':'01'}`;}if(debug)$('debug').textContent=`${state} | ${fps.toFixed(0)} FPS | ${Math.round(distance)}m | ${world.renderer.info.render.triangles} tris | ${world.renderer.info.render.calls} calls`;}
function resize(){world?.resize();fx.width=innerWidth;fx.height=innerHeight;}
function loop(now){requestAnimationFrame(loop);const realDt=Math.min((now-previous)/1000,.08);previous=now;fps=damp(fps,1/Math.max(realDt,.001),2,realDt);if(state==='playing'){let rest=realDt*speed;while(rest>0&&state==='playing'){const step=Math.min(rest,1/60);update(step);rest-=step;}}else if(state==='menu')world.setCamera(14+Math.sin(now/12000)*4,0,true);else if(state==='clearing'){clearProjectiles();finishTimer-=realDt*speed;updateParticles(realDt*speed);if(finishTimer<=0)result(true);}if(messageTimer>0){messageTimer-=realDt;$('message').classList.toggle('visible',messageTimer>0);}world.render();drawFX();hud();}
async function boot(){try{world=new GameWorld($('world'));input=new FlightInput($('world'),{pause,start});landscape=new LandscapeMode(()=>pause(true));window.addEventListener('resize',resize);$('start').onclick=start;$('resume').onclick=()=>pause();$('pause').onclick=()=>pause();$('retry').onclick=retry;$('pause-retry').onclick=retry;$('back-title').onclick=title;$('sound').onclick=()=>{audio.unlock();audio.setMuted(!audio.muted);$('sound').textContent=audio.muted?'♪×':'♫';};$('sound').textContent=audio.muted?'♪×':'♫';show('debug',debug);
  await world.load(p=>$('load-fill').style.width=`${p*100}%`);state='menu';$('start').disabled=false;$('start-label').textContent='出撃する / START';resize();world.setCamera(14,0,true);requestAnimationFrame(loop);
  const inspect=()=>({state,elapsed,distance,hp,score,kills,locks:locks.targets.length,enemies:enemies.map(e=>({id:e.id,type:e.type,hp:e.hp,screen:world.project(targetPoint(e))})),stats:{...stats},hero:{side:heroSide,height:heroHeight,bank,frame:Math.floor(elapsed*11)%4},aim:{...input.aim},touchPad:input.touchPad?{...input.touchPad}:null,lockRadius:lockRadius(innerWidth,innerHeight),held:input.held,bullets:bullets.length,lasers:lasers.length,bossHP:boss?.hp,fps,cityMeshes:world.chunks.length,materials:world.city.children.flatMap(c=>c.children.filter(o=>o.isMesh).map(o=>({name:o.material.name,textured:!!o.material.map,uv:!!o.geometry.attributes.uv}))) });
  window.__nightVector={inspect};if(debug)Object.assign(window.__nightVector,{start,retry,pause,damage:amount=>{invincible=0;damagePlayer(amount);}});
}catch(error){console.error(error);show('fatal',true);$('fatal-detail').textContent=error.message;}
}
boot();
